---
# IP Spoofing protection
- sysctl: >
    name=net.ipv4.conf.all.rp_filter
    state=present
    value=1
- sysctl: >
    name=net.ipv4.conf.default.rp_filter
    state=present
    value=1

# Ignore ICMP broadcast requests
- sysctl: >
    name=net.ipv4.icmp_echo_ignore_broadcasts
    state=present
    value=1

# Disable source packet routing
- sysctl: >
    name=net.ipv4.conf.all.accept_source_route
    state=present
    value=0
- sysctl: >
    name=net.ipv6.conf.all.accept_source_route
    state=present
    value=0 
- sysctl: >
    name=net.ipv4.conf.default.accept_source_route
    state=present
    value=0
- sysctl: >
    name=net.ipv6.conf.default.accept_source_route
    state=present
    value=0

# Ignore send redirects
- sysctl: >
    name=net.ipv4.conf.all.send_redirects
    state=present
    value=0
- sysctl: >
    name=net.ipv4.conf.default.send_redirects
    state=present
    value=0

# Block SYN attacks
- sysctl: >
    name=net.ipv4.tcp_syncookies
    state=present
    value=1
- sysctl: >
    name=net.ipv4.tcp_max_syn_backlog
    state=present
    value=2048
- sysctl: >
    name=net.ipv4.tcp_synack_retries
    state=present
    value=2
- sysctl: >
    name=net.ipv4.tcp_syn_retries
    state=present
    value=5

# Log Martians
- sysctl: >
    name=net.ipv4.conf.all.log_martians
    state=present
    value=1
- sysctl: >
    name=net.ipv4.icmp_ignore_bogus_error_responses
    state=present
    value=1

# Ignore ICMP redirects
- sysctl: >
    name=net.ipv4.conf.all.accept_redirects
    state=present
    value=0
- sysctl: >
    name=net.ipv6.conf.all.accept_redirects
    state=present
    value=0
- sysctl: >
    name=net.ipv4.conf.default.accept_redirects
    state=present
    value=0 
- sysctl: >
    name=net.ipv6.conf.default.accept_redirects
    state=present
    value=0

# Ignore Directed pings
- sysctl: >
    name=net.ipv4.icmp_echo_ignore_all
    state=present
    value=1

# REFERENCES:
# Ubuntu step 3 hardening from http://www.thefanclub.co.za/how-to/how-secure-ubuntu-1204-lts-server-part-1-basics